services:
  hans:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hans
    volumes:
      - ./storage:/app/storage
    ports:
      - "3000:3000"
      - "7860:7860"
    restart: always
